spring:
  application:
    name: inventory-failover
  cloud:
    config:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

server:
  port: 8083

management:
  tracing:
    sampling:
      probability: 1

logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  include-application-name: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://netflix:eureka@localhost:8761/eureka