spring:
    application:
      name: inventory-failover

server:
  port: 8083

management:
  tracing:
    sampling:
      probability: 1

logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  include-application-name: false