volumes:
  mssc_brewery_mysql_data:
    driver: local

services:
  mysql:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mssc_brewery_mysql_data:/var/lib/mysql

  activemq:
    image: apache/activemq-artemis:latest
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ARTEMIS_USER: user
      ARTEMIS_PASSWORD: password

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"