spring:
  application:
    name: mssc-brewery-gateway

server:
  port: 9090

management:
  tracing:
    sampling:
      probability: 1

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: false