spring:
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        serviceId: 'mssc-config-server'
      fail-fast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
      username: MyUserName
      password: MySecretPassword
  config:
    import: 'optional:configserver:'

eureka:
  client:
    serviceUrl:
      defaultZone: http://netflix:eureka@localhost:8761/eureka