server:
  port: 8082

logging:
  level:
    guru: debug
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  include-application-name: false

spring:
  application:
    name: inventory-service
  artemis:
    user: user
    password: password
  security:
    user:
      name: good
      password: beer

management:
  tracing:
    sampling:
      probability: 1
  defaults:
    metrics:
      export:
        enabled: false