server:
  port: 8888

spring:
    application:
      name: mssc-config-server
    cloud:
      config:
        server:
          git:
            uri: https://github.com/springframeworkguru/mssc-brewery-config-repo
            clone-on-start: true

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        web: DEBUG