server:
  port: 8888

spring:
    application:
      name: mssc-config-server
    cloud:
      config:
        server:
          git:
            uri: https://github.com/Bsd15/mssc-brewery-config-repo
            clone-on-start: true
            search-paths: '{application}'
    security:
      user:
        name: MyUserName
        password: MySecretPassword

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        web: DEBUG

encrypt:
  key: MySuperSecretPassword