spring:
  application:
    name: beer-service
  sql:
    init:
      mode: embedded
  jpa:
    defer-datasource-initialization: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  artemis:
    user: user
    password: password

sfg:
  brewery:
    beer-inventory-service:
      host: http://localhost:8082
      inventory-path: /api/v1/beer/{beerId}/inventory
    inventory-user: good
    inventory-password: beer

logging:
  level:
    guru:
      springframework:
        msscbeerservice:
          services: DEBUG
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  include-application-name: false

management:
  tracing:
    sampling:
      probability: 1
  defaults:
    metrics:
      export:
        enabled: false