spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    config:
      discovery:
        enabled: true
        serviceId: 'mssc-config-server'
  config:
    import: 'optional:configserver:'