spring:
  sql:
    init:
      mode: embedded
  jpa:
    defer-datasource-initialization: true

sfg:
  brewery:
    beer-inventory-service:
      host: http://localhost:8082
      inventory-path: /api/v1/beer/{beerId}/inventory
