spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    config:
      discovery:
        enabled: true
        serviceId: 'mssc-config-server'
      fail-fast: true
      username: MyUserName
      password: MySecretPassword
  config:
    import: 'optional:configserver:'

eureka:
  client:
    serviceUrl:
      defaultZone: http://netflix:eureka@localhost:8761/eureka