logging:
  level:
    guru: debug
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  include-application-name: false

server:
  port: 8081

spring:
  application:
    name: order-service
  artemis:
    user: user
    password: password

sfg:
  brewery:
    beer-service-host: http://localhost:8080

management:
  tracing:
    sampling:
      probability: 1