logging:
  level:
    guru: debug

server:
  port: 8081

spring:
  application:
    name: beer-order-service
  artemis:
    user: user
    password: password

sfg:
  brewery:
    beer-service-host: http://localhost:8080
